name: Classification_Iris
channels:
  - defaults
  - conda-forge
dependencies:
- python=3.10.14
- pip=24.0
- scikit-learn=1.5.0
- pandas= 2.2.2
- pip:
  - mlflow == 2.14.1
  - numpy == 1.26.4
  - seaborn == 0.13.2