name: clase1
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.0
  - scikit-learn=1.5.0
  - pandas=2.2.2
  - pip:
      - mlflow==2.14.1
      - wandb==0.17.2
      - numpy==1.26.4